apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJnaGNyLmlvIjogewogICAgICAiYXV0aCI6ICJhV3g1WVMxcmNuVm5iRzkyT21kb2NGOVFTbVpMTVhWeVkybFVTV0ZJUWpOVFFuVkJZWEZhYlhsdFpqQktkazB6WlRSSWJEVT0iCiAgICB9CiAgfQp9Cg==
type: kubernetes.io/dockerconfigjson
